"""Yaozarrs-based backends for OME-Zarr v0.5."""

from __future__ import annotations

import json
import os
import tempfile
import threading
import warnings
from abc import abstractmethod
from collections.abc import Iterator, Mapping, MutableMapping
from contextlib import suppress
from copy import deepcopy
from pathlib import Path
from typing import TYPE_CHECKING, Any, Generic, TypeVar, cast

import numpy as np

from ome_writers import __version__
from ome_writers._backends._backend import ArrayBackend
from ome_writers._backends._chunk_buffer import ChunkBuffer
from ome_writers._schema import is_channel_dim

try:
    from yaozarrs import DimSpec, v05
    from yaozarrs.write.v05 import Bf2RawBuilder, PlateBuilder, prepare_image
except ImportError as e:
    raise ImportError(
        f"{__name__} requires yaozarrs with write support: "
        "`pip install yaozarrs[write-zarr]`."
    ) from e


if TYPE_CHECKING:
    from collections.abc import Callable, Sequence
    from typing import Literal, Protocol

    from typing_extensions import Self
    from yaozarrs.write.v05._write import CompressionName

    from ome_writers._backends._backend import ArrayLike
    from ome_writers._router import FrameRouter
    from ome_writers._schema import (
        AcquisitionSettings,
        Dimension,
        Plate,
        Position,
    )

    class YaozArray(Protocol):
        """Protocol for array-like objects that support shape attribute."""

        @property
        def shape(self) -> tuple[int, ...]: ...

        def __setitem__(self, index: Any, val: Any) -> Any: ...

        def resize(self, new_shape: Sequence[int]) -> None: ...


# Array type generated by yaozarrs writers
_AT = TypeVar("_AT", bound="YaozArray")
YAOZARRS_COMPRESSION_OPTIONS = {"blosc-zstd", "blosc-lz4", "zstd", "none"}


class YaozarrsBackend(ArrayBackend, Generic[_AT]):
    """Base backend using yaozarrs for OME-Zarr v0.5 structure.

    Subclasses must define the `writer` class attribute to specify which
    yaozarrs writer to use (e.g., "zarr", "tensorstore").
    """

    def __init__(self) -> None:
        self._arrays: list[_AT] = []
        self._image_group_paths: list[str] = []  # Parallel to _arrays, for metadata
        self._meta_mirrors: dict[str, JsonDocumentMirror] = {}  # grouppath -> mirror
        # Mirror for the *parent* root group's zarr.json, used for
        # set_global_metadata(). For single-position layouts this is the same
        # object as self._meta_mirrors["."]; for multi-position (bf2raw) and
        # plate layouts it is a separate mirror over <root>/zarr.json.
        self._root_meta_mirror: JsonDocumentMirror | None = None
        self._finalized = False
        self._root: Path | None = None
        self._chunk_buffers: list[ChunkBuffer] | None = None

    @abstractmethod
    def _get_yaozarrs_writer(
        self,
    ) -> Literal["zarr", "tensorstore"] | Callable[..., Any]:
        """Return the writer to use for array creation.

        Subclasses can override to provide a custom CreateArrayFunc.
        """

    def _post_prepare(self, settings: AcquisitionSettings) -> None:
        """Hook called after yaozarrs creates the structure, before metadata caching.

        Subclasses can override to do additional setup (e.g., create streams).
        """

    def is_incompatible(self, settings: AcquisitionSettings) -> Literal[False] | str:
        """Check if settings are incompatible with yaozarrs backend.

        Returns a string describing the incompatibility, or False if compatible.
        """
        cls_name = self.__class__.__name__

        # Check for supported compression
        compression = settings.compression
        if compression and compression not in YAOZARRS_COMPRESSION_OPTIONS:
            return (  # pragma: no cover
                f"Compression '{compression}' is not supported by {cls_name}. "
                f"Supported: {YAOZARRS_COMPRESSION_OPTIONS}."
            )

        return False

    def prepare(self, settings: AcquisitionSettings, router: FrameRouter) -> None:
        """Initialize OME-Zarr storage structure."""

        self._finalized = False
        self._root = root = Path(settings.output_path).expanduser().resolve()
        positions = settings.positions

        # Build storage metadata
        storage_dims = settings.array_storage_dimensions
        shape = tuple(d.count if d.count is not None else 1 for d in storage_dims)
        dtype = settings.dtype
        chunks, shards = _get_chunks_and_shards(storage_dims)
        # Build a per-position image model so each position can carry its own
        # spatial translation (from Position.x_coord/y_coord/z_coord).  Shape and
        # dtype are shared across positions.
        storage_dims_list = list(storage_dims)
        images: list[v05.Image] = [
            _build_yaozarrs_image_model(storage_dims_list, dtype, position=pos)
            for pos in positions
        ]

        compression = cast("CompressionName", settings.compression or "none")

        # Get writer from hook (subclasses can override)
        writer = self._get_yaozarrs_writer()

        # Plate mode
        if settings.plate is not None:
            # mapping of {(row, column): [(position_index, Position), ...]}
            well_positions = {}
            for i, pos in enumerate(positions):
                key = (pos.plate_row, pos.plate_column)
                well_positions.setdefault(key, []).append((i, pos))

            # Build plate metadata and arrays
            builder = PlateBuilder(
                root,
                plate=_build_yaozarrs_plate_model(settings.plate, well_positions),
                overwrite=settings.overwrite,
                chunks=chunks,
                shards=shards,
                writer=writer,
                compression=compression,
            )

            for (row, col), pos_list in well_positions.items():
                images_dict = {
                    pos.name: (images[idx], [(shape, dtype)]) for idx, pos in pos_list
                }
                builder.add_well(row=row, col=col, images=images_dict)

            _, all_arrays = builder.prepare()
            # Map position index to array path and store arrays
            self._image_group_paths = [
                f"{pos.plate_row}/{pos.plate_column}/{pos.name}" for pos in positions
            ]
            self._arrays = [
                all_arrays[f"{parent}/0"] for parent in self._image_group_paths
            ]

        # Single position
        elif len(positions) == 1:
            _, all_arrays = prepare_image(
                root,
                images[0],
                datasets=[(shape, dtype)],
                overwrite=settings.overwrite,
                chunks=chunks,
                shards=shards,
                writer=writer,
                compression=compression,
            )
            self._image_group_paths = ["."]
            self._arrays = [all_arrays["0"]]  # ty: ignore[invalid-assignment]

        # Multi-position (bf2raw layout)
        else:
            builder = Bf2RawBuilder(
                root,
                overwrite=settings.overwrite,
                chunks=chunks,
                shards=shards,
                writer=writer,
                compression=compression,
            )
            for idx, pos in enumerate(positions):
                builder.add_series(_get_series_name(pos), images[idx], [(shape, dtype)])

            _, all_arrays = builder.prepare()
            self._image_group_paths = [_get_series_name(pos) for pos in positions]
            self._arrays = [
                all_arrays[f"{parent}/0"] for parent in self._image_group_paths
            ]

        # Post-prepare hook (subclasses can do additional work)
        self._post_prepare(settings)

        # Cache metadata immediately after creation
        # This is used later for get_metadata() and update_metadata()
        self._cache_metadata_from_arrays(root)
        self._cache_root_meta_mirror(root)

        # Initialize chunk buffering if beneficial
        if self._should_use_chunk_buffering(storage_dims):
            # Extract shapes for buffer initialization
            index_dims = storage_dims[:-2]  # Exclude frame dims
            frame_dims = storage_dims[-2:]  # Y, X

            index_shape = tuple(d.count for d in index_dims)
            chunk_shape = tuple(
                d.chunk_size if d.chunk_size is not None else 1 for d in index_dims
            )
            frame_shape = tuple(d.count for d in frame_dims)

            # Create one buffer per position
            self._chunk_buffers = [
                ChunkBuffer(
                    index_shape=index_shape,
                    chunk_shape=chunk_shape,
                    frame_shape=frame_shape,
                    dtype=dtype,
                )
                for _ in range(len(positions))
            ]
        else:
            self._chunk_buffers = None

    def _ensure_array_size(
        self, position_index: int, indices: Sequence[tuple[int, ...]]
    ) -> None:
        """Resize array if needed to accommodate the given indices.

        This method calculates the maximum extent across all provided indices
        and resizes the array once if needed. It also updates chunk buffer
        index_shape for buffered backends.
        """
        array = self._arrays[position_index]
        current_shape = list(array.shape)
        new_shape = current_shape.copy()

        # Find maximum extent across all indices
        for storage_idx in indices:
            for i, idx_val in enumerate(storage_idx):
                new_shape[i] = max(new_shape[i], idx_val + 1)

        # Resize only once if needed
        if new_shape != current_shape:
            self._resize(array, new_shape)
            if self._chunk_buffers:
                self._chunk_buffers[position_index].index_shape = new_shape[:-2]

    def write(
        self,
        position_index: int,
        index: tuple[int, ...],
        frame: np.ndarray,
        *,
        frame_metadata: dict[str, Any] | None = None,
    ) -> None:
        """Write frame to specified location with auto-resize for unlimited dims."""
        if self._finalized:  # pragma: no cover
            raise RuntimeError("Cannot write after finalize().")

        # Resize array if needed to accommodate index
        self._ensure_array_size(position_index, [index])

        # Route to buffered or direct write
        array = self._arrays[position_index]
        if self._chunk_buffers:
            self._write_with_buffering(
                self._chunk_buffers[position_index], array, index, frame
            )
        else:
            self._write(array, index, frame)

        self._store_frame_metadata(position_index, index, frame_metadata)

    def advance(self, indices: Sequence[tuple[int, tuple[int, ...]]]) -> None:
        """Efficiently resize arrays once based on maximum extent of skipped indices.

        For Zarr backends, skipping frames only requires resizing arrays to
        accommodate the new indices. No data is written - skipped regions use
        the array's fill_value.
        """
        if self._finalized:  # pragma: no cover
            raise RuntimeError("Cannot advance after finalize().")

        # Group indices by position
        position_indices: dict[int, list[tuple[int, ...]]] = {}
        for pos_idx, storage_idx in indices:
            position_indices.setdefault(pos_idx, []).append(storage_idx)

        # For each position, resize once to accommodate all indices
        for pos_idx, storage_indices in position_indices.items():
            self._ensure_array_size(pos_idx, storage_indices)

    def _store_frame_metadata(
        self,
        position_index: int,
        index: tuple[int, ...],
        frame_metadata: dict[str, Any] | None,
    ) -> None:
        # Accumulate frame metadata with storage index
        if frame_metadata is not None:
            mirror = self._meta_mirrors[self._image_group_paths[position_index]]
            mirror.append_frame_metadata({**frame_metadata, "storage_index": index})

    def _write_with_buffering(
        self,
        buffer: ChunkBuffer,
        array: _AT,
        index: tuple[int, ...],
        frame: np.ndarray,
    ) -> None:
        """Write frame using chunk buffering.

        If desired, subclasses can override this to customize buffering behavior.
        """
        chunk_coords = buffer.add_frame(index, frame)

        # If chunk is complete, flush it
        if chunk_coords is not None:
            storage_start, chunk_data = buffer.get_chunk_for_flush(chunk_coords)
            self._write_chunk(array, storage_start, chunk_data)

    def _write_chunk(
        self, array: _AT, start_index: tuple[int, ...], chunk_data: np.ndarray
    ) -> None:
        """Write a complete chunk to the array.

        This is called when the chunk buffer indicates a chunk is complete and ready
        to be flushed to storage.
        """
        slices = tuple(
            slice(start, start + size)
            for start, size in zip(start_index, chunk_data.shape, strict=False)
        )
        self._write(array, slices, chunk_data)

    def _write(self, array: _AT, index: tuple[int, ...], frame: np.ndarray) -> None:
        """Write frame to array at specified index."""
        array[index] = frame

    def get_arrays(self) -> Sequence[ArrayLike]:
        """Return array-like objects for each position."""
        if self._arrays:
            return self._arrays  # type: ignore
        if self._finalized and self._root and self._image_group_paths:
            return self._reopen_arrays()
        raise RuntimeError("Backend not prepared. Call prepare() first.")

    def _reopen_arrays(self) -> Sequence[ArrayLike]:
        """Reopen arrays read-only from disk after finalization."""
        assert self._root is not None
        arrays = []
        for group_path in self._image_group_paths:
            arrays.append(_open_any_zarr_readonly(self._root / group_path / "0"))
        return arrays

    def get_metadata(self) -> dict[str, dict]:
        """Get metadata from all array groups in the zarr hierarchy.

        Returns a dict mapping group paths (relative to root) to the *attributes*
        section of the corresponding zarr.json files (not the entire file).

        Use `update_metadata()` to modify and write back.

        Note: frame_metadata (appended during writes) is not included in the returned
        value here, but is written to disk when metadata is flushed.

        Returns
        -------
        dict[str, dict]
            Mapping of group paths to .zattrs dicts, or empty dict if not prepared.

        Examples
        --------
        For single position:
            {".": {"ome": {...}}}  # root group attrs

        For multi-position:
            {"pos0": {"ome": {...}}, "pos1": {"ome": {...}}}

        For plates:
            {"A/1/field_0": {"ome": {...}}, "A/2/field_0": {"ome": {...}}}
        """
        if not self._meta_mirrors:  # pragma: no cover
            return {}

        return {
            path: deepcopy(mirror.get("attributes", {}))
            for path, mirror in self._meta_mirrors.items()
        }

    def update_metadata(self, metadata: dict[str, dict]) -> None:
        """Update metadata for all array groups in the zarr hierarchy.

        Parameters
        ----------
        metadata : dict[str, dict]
            Mapping of group paths to .zattrs dicts. Keys should match those
            returned by get_metadata(). Values are dicts that will be written
            to the corresponding .zattrs files.

        Raises
        ------
        KeyError
            If a path in metadata doesn't correspond to a group.
        RuntimeError
            If backend is not prepared.
        """
        if not self._meta_mirrors:  # pragma: no cover
            raise RuntimeError("Backend not prepared. Call prepare() first.")

        if self._root is None:  # pragma: no cover
            warnings.warn("Root path is unknown. Cannot update metadata.", stacklevel=2)
            return

        for path, attrs in metadata.items():
            if path not in self._meta_mirrors:
                raise KeyError(f"Unknown path: {path}")

            mirror = self._meta_mirrors[path]
            mirror["attributes"] = deepcopy(attrs)
            mirror.flush()

    def finalize(self) -> None:
        """Flush and release resources."""
        if not self._finalized:
            self._finalize_chunk_buffers()
            for mirror in self._meta_mirrors.values():
                mirror.flush()
            root_mir = self._root_meta_mirror
            if root_mir is not None and root_mir not in self._meta_mirrors.values():
                root_mir.flush()
            self._arrays.clear()
            # Keep _image_group_paths for post-close reading
            self._finalized = True

    def _finalize_chunk_buffers(self) -> None:
        # Flush any remaining partial chunks.
        # NOTE:
        # This is defensive code that should never execute in normal operation.
        # With sequential frame writing via OMEStream.append(), chunks are either:
        # (1) fully complete and auto-flushed immediately via _write_with_buffering
        # (2) never started (no frames written yet). This code only executes if
        # frames are written out-of-order (e.g., direct backend.write() calls) or if
        # there's a bug in chunk completion logic. It ensures no buffered data is
        # silently lost during finalization.
        if self._chunk_buffers:  # pragma: no cover
            for pos_idx, buffer in enumerate(self._chunk_buffers):
                if self._arrays:  # Arrays may have been cleared already
                    array = self._arrays[pos_idx]
                    for storage_start, chunk_data in buffer.flush_all_partial():
                        self._write_chunk(array, storage_start, chunk_data)
        self._chunk_buffers = None

    def _resize(self, array: _AT, new_shape: Sequence[int]) -> None:
        """Resize array to new shape."""
        array.resize(new_shape)

    def _cache_root_meta_mirror(self, root: Path) -> None:
        """Cache a mirror for the parent root group's zarr.json.

        For single-position layouts the parent root group *is* the image
        group, so we reuse the existing mirror. For multi-position (bf2raw)
        and plate layouts, open a new mirror over `<root>/zarr.json`.
        """
        # Single-position: parent root group is the image group itself.
        if self._image_group_paths == ["."]:
            self._root_meta_mirror = self._meta_mirrors.get(".")
            return

        root_json = root / "zarr.json"
        if root_json.exists():
            self._root_meta_mirror = JsonDocumentMirror(root_json).load()
        else:  # pragma: no cover
            self._root_meta_mirror = None

    def set_global_metadata(self, namespace: str, metadata: Mapping[str, Any]) -> None:
        """Write acquisition-level metadata to the parent root group's attrs.

        The value is stored under `attributes[namespace]` in
        `<root>/zarr.json`. Same namespace replaces prior value; different
        namespaces are stored as siblings. No merging.
        """
        if (mirror := self._root_meta_mirror) is None:  # pragma: no cover
            raise RuntimeError("Backend not prepared. Call prepare() first.")

        mirror.set_attribute_namespace(namespace, metadata)
        mirror.flush()

    def _cache_metadata_from_arrays(self, root: Path) -> None:
        """Cache metadata from parent groups.

        Reads zarr.json and caches their attributes in position order.
        """
        for group_path in self._image_group_paths:
            if (zarr_json := root / group_path / "zarr.json").exists():
                self._meta_mirrors[group_path] = JsonDocumentMirror(zarr_json).load()

    def _should_use_chunk_buffering(self, storage_dims: list[Dimension]) -> bool:
        """Check if chunk buffering would be beneficial.

        Returns True if any index dimension (excluding last 2 frame dims)
        has chunk_size > 1.
        """
        # Only check index dimensions (exclude frame dimensions)
        for dim in storage_dims[:-2]:
            if dim.chunk_size is not None and dim.chunk_size > 1:
                return True
        return False


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def _open_any_zarr_readonly(path: Path) -> ArrayLike:
    """Open a zarr v3 array read-only, using whichever library is available."""
    with suppress(ImportError):
        import tensorstore as ts

        spec = {"driver": "zarr3", "kvstore": {"driver": "file", "path": str(path)}}
        return ts.open(spec, read=True, write=False).result()  # type: ignore

    with suppress(ImportError):
        import zarr

        return zarr.open_array(path, mode="r")  # pyright: ignore[reportReturnType]

    raise NotImplementedError(
        "Post-close viewing requires zarr or tensorstore. "
        "Pip install with `ome-writers[zarr]` or `ome-writers[tensorstore]`."
    )


def _get_chunks_and_shards(
    dims: list[Dimension],
) -> tuple[tuple[int, ...], tuple[int, ...] | None]:
    """Compute chunk and shard sizes from dimensions."""
    chunks = []
    shards = []
    has_shards = False
    n = len(dims)

    for i, dim in enumerate(dims):
        # Chunks
        if dim.chunk_size is not None:
            chunks.append(dim.chunk_size)
        elif i >= n - 2:  # Last 2 dims (spatial)
            chunks.append(dim.count)
        else:
            chunks.append(1)

        # Shards
        if dim.shard_size_chunks is not None:
            # multiply shard_size_chunks by chunk size
            # to get shard shape in pixels (which is what yaozarrs expects)
            shards.append(chunks[-1] * dim.shard_size_chunks)
            has_shards = True
        else:
            shards.append(chunks[-1])  # Default to chunk size

    return tuple(chunks), tuple(shards) if has_shards else None


def _build_yaozarrs_image_model(
    dims: list[Dimension], dtype: str, position: Position | None = None
) -> v05.Image:
    """Build yaozarrs v05 Image metadata from Dimensions.

    If `position` is given, its `x_coord`/`y_coord`/`z_coord` override the
    translation of the corresponding spatial dims so that each per-position
    image in a multi-position acquisition gets its own origin. See
    `_position_translation_by_dim_index` for the mapping rules.
    """
    pos_translations = _position_translation_by_dim_index(dims, position)

    dim_specs = [
        DimSpec(
            name=dim.name,
            size=dim.count,
            type=dim.type,
            unit=dim.unit,
            scale=1.0 if dim.scale is None else dim.scale,
            translation=pos_translations.get(i, dim.translation),
        )
        for i, dim in enumerate(dims)
    ]
    channel_dim = next((d for d in dims if is_channel_dim(d)), None)
    if channel_dim is not None and channel_dim.coords:
        omero_channels = []
        for c in channel_dim.coords:
            # Default color to white if not specified
            color = (
                c.color.as_hex(format="long").lstrip("#").upper()
                if c.color
                else "FFFFFF"
            )
            # Default to full range window for the given dtype
            dtype_min = np.iinfo(dtype).min
            dtype_max = np.iinfo(dtype).max
            window = v05.OmeroWindow(
                min=dtype_min, max=dtype_max, start=dtype_min, end=dtype_max
            )
            omero_channels.append(
                v05.OmeroChannel(label=c.name, color=color, window=window)
            )

        omero = v05.Omero(channels=omero_channels)
    else:
        omero = None
    return v05.Image(multiscales=[v05.Multiscale.from_dims(dim_specs)], omero=omero)


def _position_translation_by_dim_index(
    dims: list[Dimension], pos: Position | None
) -> dict[int, float]:
    """Map `Position.x_coord/y_coord/z_coord` onto target dim indices.

    Strategy:

    1. Name match (case-insensitive) on `"x"`, `"y"`, `"z"` wins first. This is
       the NGFF canonical labeling and what the vast majority of users will
       have (via `StandardAxis` / `useq_to_acquisition_settings`).
    2. For X and Y *only*, fall back to the trailing two dims of `dims` (the
       schema-guaranteed frame dims): the last dim gets `x_coord`, the
       second-to-last gets `y_coord`, provided they are space-typed and
       weren't already claimed by a name match. This handles non-canonical
       names like `"row"`/`"col"`.
    3. Z has *no* positional fallback. ome-writers doesn't mandate canonical
       axis names and doesn't mandate a ZYX dim order (`storage_order` can
       be `"acquisition"` or a custom list), so there is no unambiguous
       positional slot for Z the way there is for the frame-last X/Y pair.
       A future schema change — e.g. an explicit `spatial_role` on
       `Dimension`, or a structured position coord map keyed by dim name —
       could lift this restriction. Until then, per-position Z translation
       requires naming the Z axis `"z"` (case-insensitive).

    Returns
    -------
    dict[int, float]
        Mapping of dim index to translation value for spatial dims with position coords.
        Example: {0: 1.5, 3: 0.2} means the dim at index 0 has translation 1.5 and the
        dim at index 3 has translation 0.2.
    """
    if pos is None:
        return {}

    # Step 1: name match
    name_to_index: dict[str, int] = {}
    for i, d in enumerate(dims):
        lower = d.name.lower()
        if lower in ("x", "y", "z") and lower not in name_to_index:
            name_to_index[lower] = i

    out: dict[int, float] = {}
    for axis, value in (("x", pos.x_coord), ("y", pos.y_coord), ("z", pos.z_coord)):
        if value is not None and (idx := name_to_index.get(axis)) is not None:
            out[idx] = value

    # Step 2: positional fallback for the frame X/Y dims only.
    n = len(dims)
    if (
        "x" not in name_to_index
        and pos.x_coord is not None
        and n >= 1
        and dims[-1].type == "space"
    ):
        out.setdefault(n - 1, pos.x_coord)
    if (
        "y" not in name_to_index
        and pos.y_coord is not None
        and n >= 2
        and dims[-2].type == "space"
    ):
        out.setdefault(n - 2, pos.y_coord)

    return out


def _get_series_name(pos: Position) -> str:
    """Get unique series name for a position.

    For positions with grid coordinates, combines name with grid coordinates
    to ensure uniqueness. Otherwise, returns the position name as-is.
    """
    if pos.grid_row is not None and pos.grid_column is not None:
        return f"{pos.name}_{pos.grid_row}_{pos.grid_column}"
    return pos.name


def _build_yaozarrs_plate_model(
    plate: Plate, well_positions: dict[tuple[str, str], list[tuple[int, Position]]]
) -> v05.Plate:
    """Build yaozarrs v05 Plate metadata from ome-writers Plate schema."""
    return v05.Plate(
        plate=v05.PlateDef(
            name=plate.name,
            rows=[v05.Row(name=name) for name in plate.row_names],
            columns=[v05.Column(name=name) for name in plate.column_names],
            wells=[
                v05.PlateWell(
                    path=f"{row}/{col}",
                    rowIndex=plate.row_names.index(row),
                    columnIndex=plate.column_names.index(col),
                )
                for row, col in well_positions
            ],
        )
    )


class JsonDocumentMirror(MutableMapping[str, Any]):
    """In-memory mirror of a .json document with dirty tracking."""

    __slots__ = ("_data", "_dirty", "_frame_metadata", "_lock", "_path")

    def __init__(self, path: Path | str) -> None:
        self._path = Path(path)
        self._data: dict[str, Any] = {}
        self._dirty = False
        self._lock = threading.Lock()  # for thread safety

        # store this outside of _data for easy access and data integrity
        self._frame_metadata: list[dict[str, Any]] = []

    def append_frame_metadata(self, metadata: dict[str, Any]) -> None:
        """Append frame metadata entry."""
        self._frame_metadata.append(metadata)
        self._dirty = True

    def mark_dirty(self) -> None:
        """Mark this mirror as having unflushed in-memory modifications."""
        with self._lock:
            self._dirty = True

    def set_attribute_namespace(self, namespace: str, value: Mapping[str, Any]) -> None:
        """Set `attributes[namespace] = deepcopy(value)` atomically."""
        with self._lock:
            attrs = cast("dict[str, Any]", self._data.setdefault("attributes", {}))
            attrs[namespace] = deepcopy(dict(value))
            self._dirty = True

    def __getitem__(self, key: str) -> Any:
        with self._lock:
            return self._data[key]

    def __setitem__(self, key: str, value: Any) -> None:
        with self._lock:
            self._data[key] = value
            self._dirty = True

    def __delitem__(self, key: str) -> None:  # pragma: no cover
        with self._lock:
            del self._data[key]
            self._dirty = True

    def __iter__(self) -> Iterator[str]:  # pragma: no cover
        return iter(self._data)

    def __len__(self) -> int:  # pragma: no cover
        return len(self._data)

    def flush(self, indent: int | None = None) -> None:
        """Write data to disk if dirty."""
        with self._lock:
            if self._dirty:
                # Ensure frame_metadata is up-to-date in the document
                self.ome_writers["frame_metadata"] = self._frame_metadata

                # NOTE:
                # we could consider attempting to serialize certain sub-sections here
                # (e.g., "ome_writers.frame_metadata", which contains user-data)
                # and pop them from the metadata if they fail to serialize...
                # for now it's all-or-nothing
                try:
                    json_str = json.dumps(self._data, indent=indent)
                except (TypeError, ValueError) as e:  # pragma: no cover
                    raise ValueError(
                        f"Failed to serialize zarr.json for {self._path}:\n{e}"
                    ) from e

                # Write via temp file and atomically replace destination to
                # avoid exposing partially written JSON to concurrent readers.
                tmp_path: str | None = None
                try:
                    with tempfile.NamedTemporaryFile(
                        mode="w",
                        encoding="utf-8",
                        dir=self._path.parent,
                        prefix=f"{self._path.name}.",
                        suffix=".tmp",
                        delete=False,
                    ) as tmp:
                        tmp.write(json_str)
                        tmp_path = tmp.name
                    os.replace(tmp_path, self._path)
                    tmp_path = None  # replace consumed it; skip cleanup
                finally:
                    if tmp_path is not None:
                        with suppress(FileNotFoundError):
                            Path(tmp_path).unlink()
                self._dirty = False

    def load(self) -> Self:
        """Load data from disk."""
        with self._lock:
            if self._dirty:  #  pragma: no cover
                raise RuntimeError("Cannot load while dirty. Flush first.")

            if self._path.exists():
                # NB: could use streaming parser for large files, but zarr.json
                # are typically small enough to read fully into memory
                content = self._path.read_text()
                self._data = cast("dict[str, Any]", json.loads(content))
            else:
                self._data = {}  # pragma: no cover
            self._dirty = False
        return self

    @property
    def ome_writers(self) -> dict[str, Any]:
        """Get ome_writers dict from attributes."""
        attrs = cast("dict", self._data.setdefault("attributes", {}))
        return attrs.setdefault("ome_writers", {"version": __version__})
